# also change node version in .travis.yml file
FROM node:10-alpine AS builder

WORKDIR /build
COPY package*.json .babelrc /build/
COPY app /build/app/
RUN npm install && npm run _production:build

FROM node:10-alpine

EXPOSE 5000

ENV HOME=/home/app/
RUN mkdir -p ${HOME}
WORKDIR ${HOME}

COPY --from=builder /build/dist ${HOME}/dist
COPY .env* .sequelizerc package*.json Versionfile ${HOME}/

RUN npm install --production &&\
    chown -R node:node .

USER node

CMD ["npm", "run", "_production"]
